// <auto-generated />
using FoodApp.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodApp.Migrations
{
    [DbContext(typeof(FoodAppContext))]
    partial class FoodAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodApp.Domain.Model.Food", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FoodGroupCategory")
                        .HasColumnType("int");

                    b.Property<string>("FoodGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingSize")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Asparagus",
                            ServingSize = "\"125 mL, � cup, 6 spears\""
                        },
                        new
                        {
                            Id = 2L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "\"Beans, green\"",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 3L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Bok choy/Chinese cabbage (Choi sum)",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 4L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Broccoli",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 5L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Brussels sprouts",
                            ServingSize = "\"125 mL, � cup, 4 sprouts\""
                        },
                        new
                        {
                            Id = 6L,
                            FoodGroupCategory = 2,
                            FoodGroupId = "vf",
                            Foods = "Carrots",
                            ServingSize = "\"125 mL, � cup, 1 large\""
                        },
                        new
                        {
                            Id = 7L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Chard",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 8L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Dandelion greens",
                            ServingSize = "\"250 mL, 1 cup raw\""
                        },
                        new
                        {
                            Id = 9L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Endive",
                            ServingSize = "\"250 mL, 1 cup\""
                        },
                        new
                        {
                            Id = 10L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Fiddleheads",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 11L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Kale/collards",
                            ServingSize = "\"250 mL, 1 cup raw\""
                        },
                        new
                        {
                            Id = 12L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Leeks",
                            ServingSize = "\"125 mL, � cup, � leek\""
                        },
                        new
                        {
                            Id = 13L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "\"Lettuce, romaine\"",
                            ServingSize = "\"250 mL, 1 cup raw\""
                        },
                        new
                        {
                            Id = 14L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Mesclun mix",
                            ServingSize = "\"250 mL, 1 cup raw\""
                        },
                        new
                        {
                            Id = 15L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Mustard greens",
                            ServingSize = "\"250 mL, 1 cup raw\""
                        },
                        new
                        {
                            Id = 16L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Okra",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 17L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Peas",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 18L,
                            FoodGroupCategory = 2,
                            FoodGroupId = "vf",
                            Foods = "Pumpkin",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 19L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Seaweed",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 20L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Snow peas",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 21L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Spinach",
                            ServingSize = "\"250 mL, 1 cup raw\""
                        },
                        new
                        {
                            Id = 22L,
                            FoodGroupCategory = 2,
                            FoodGroupId = "vf",
                            Foods = "Squash",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 23L,
                            FoodGroupCategory = 2,
                            FoodGroupId = "vf",
                            Foods = "Sweet potato",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 24L,
                            FoodGroupCategory = 2,
                            FoodGroupId = "vf",
                            Foods = "Yam",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 25L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "\"Apricot, fresh\"",
                            ServingSize = "3 fruits"
                        },
                        new
                        {
                            Id = 26L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Cantaloupe",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 27L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Mango",
                            ServingSize = "\"125 mL, � cup, � fruit\""
                        },
                        new
                        {
                            Id = 28L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Nectarine",
                            ServingSize = "1 fruit"
                        },
                        new
                        {
                            Id = 29L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Papaya",
                            ServingSize = "� fruit"
                        },
                        new
                        {
                            Id = 30L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Peach",
                            ServingSize = "1 medium"
                        },
                        new
                        {
                            Id = 31L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Apple",
                            ServingSize = "1 medium"
                        },
                        new
                        {
                            Id = 32L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Avocado",
                            ServingSize = "� fruit"
                        },
                        new
                        {
                            Id = 33L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Bamboo shoots",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 34L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Banana",
                            ServingSize = "1 medium"
                        },
                        new
                        {
                            Id = 35L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "\"Beans, yellow\"",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 36L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Beets",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 37L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Berries",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 38L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Bitter melon",
                            ServingSize = "\"125 mL, � cup, � pod\""
                        },
                        new
                        {
                            Id = 39L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Cabbage",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 40L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Cauliflower",
                            ServingSize = "\"125 mL, � cup, 4 flowerets\""
                        },
                        new
                        {
                            Id = 41L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Celery",
                            ServingSize = "1 medium stalk"
                        },
                        new
                        {
                            Id = 42L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Chayote",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 43L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Cherries",
                            ServingSize = "20"
                        },
                        new
                        {
                            Id = 44L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Corn",
                            ServingSize = "\"1 ear, 125 mL, � cup\""
                        },
                        new
                        {
                            Id = 45L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Cucumber",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 46L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Dried fruit",
                            ServingSize = "\"60 mL, � cup\""
                        },
                        new
                        {
                            Id = 47L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Eggplant",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 48L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "\"Fig, fresh\"",
                            ServingSize = "2 medium"
                        },
                        new
                        {
                            Id = 49L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Grapefruit",
                            ServingSize = "� fruit"
                        },
                        new
                        {
                            Id = 50L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Grapes",
                            ServingSize = "20 fruits"
                        },
                        new
                        {
                            Id = 51L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Guava",
                            ServingSize = "\"125 mL, � cup, 1 fruit\""
                        },
                        new
                        {
                            Id = 52L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Honeydew",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 53L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "100% fruit juice",
                            ServingSize = "\"125 mL, 1/2 cup\""
                        },
                        new
                        {
                            Id = 54L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Kiwi",
                            ServingSize = "1 large fruit"
                        },
                        new
                        {
                            Id = 55L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Kohlrabi",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 56L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Lettuce (example: iceberg or butterhead)",
                            ServingSize = "\"250 mL, 1 cup raw\""
                        },
                        new
                        {
                            Id = 57L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Lychee",
                            ServingSize = "10 fruits"
                        },
                        new
                        {
                            Id = 58L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Mixed vegetables",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 59L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Mushrooms",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 60L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Orange",
                            ServingSize = "1 medium"
                        },
                        new
                        {
                            Id = 61L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Pear",
                            ServingSize = "1 medium"
                        },
                        new
                        {
                            Id = 62L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "\"Peppers, bell\"",
                            ServingSize = "\"125 mL, � cup, � medium\""
                        },
                        new
                        {
                            Id = 63L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Pineapple",
                            ServingSize = "\"125 mL, � cup, 1 slice\""
                        },
                        new
                        {
                            Id = 64L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Plantain",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 65L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Plum",
                            ServingSize = "1 fruit"
                        },
                        new
                        {
                            Id = 66L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Potato",
                            ServingSize = "\"125 mL, � cup, � medium\""
                        },
                        new
                        {
                            Id = 67L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Radishes",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 68L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Rhubarb",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 69L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Tomato",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 70L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Tomato sauce",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 71L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Turnip",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 72L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "\"Vegetable juice, lower sodium\"",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 73L,
                            FoodGroupCategory = 0,
                            FoodGroupId = "vf",
                            Foods = "Watermelon",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 74L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Zucchini",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 75L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "\"Pepper, sweet, green\"",
                            ServingSize = "\"125 mL, � cup, � medium\""
                        },
                        new
                        {
                            Id = 76L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "vf",
                            Foods = "Edemame (soy beans)",
                            ServingSize = "\"125 mL, � cup\""
                        },
                        new
                        {
                            Id = 77L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "Barley",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 78L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Bagel, whole grain\"",
                            ServingSize = "\"� bagel, 45 g\""
                        },
                        new
                        {
                            Id = 79L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Bread, pumpernickel or rye\"",
                            ServingSize = "\"1 slice, 35 g\""
                        },
                        new
                        {
                            Id = 80L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Bread, whole grain\"",
                            ServingSize = "\"1 slice, 35 g\""
                        },
                        new
                        {
                            Id = 81L,
                            FoodGroupCategory = 1,
                            FoodGroupId = "gr",
                            Foods = "Bulgur",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 82L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Cereal, cold, whole grain\"",
                            ServingSize = "30 g"
                        },
                        new
                        {
                            Id = 83L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Cereal, hot, whole grain (example: oatmeal)\"",
                            ServingSize = "\"150 g, 175 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 84L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Crackers, rye \"",
                            ServingSize = "30 g"
                        },
                        new
                        {
                            Id = 85L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Muffin, whole grain\"",
                            ServingSize = "\"�, 35 g\""
                        },
                        new
                        {
                            Id = 86L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "Quinoa",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 87L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Rice, brown\"",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 88L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Pasta/noodles, whole grain\"",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 89L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Pita, whole wheat\"",
                            ServingSize = "\"� pita, 35 g\""
                        },
                        new
                        {
                            Id = 90L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Tortilla, corn\"",
                            ServingSize = "\"� piece, 35 g\""
                        },
                        new
                        {
                            Id = 91L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Tortilla, whole wheat\"",
                            ServingSize = "\"� piece, 35 g\""
                        },
                        new
                        {
                            Id = 92L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "Bannock",
                            ServingSize = "\"1 medium, 35 g\""
                        },
                        new
                        {
                            Id = 93L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Baguette, French\"",
                            ServingSize = "\"1 slice, 35 g\""
                        },
                        new
                        {
                            Id = 94L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Bread, white\"",
                            ServingSize = "\"1 slice, 35 g\""
                        },
                        new
                        {
                            Id = 95L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Cereal, cold\"",
                            ServingSize = "30 g"
                        },
                        new
                        {
                            Id = 96L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Cereal, hot, for example: cream of wheat\"",
                            ServingSize = "\"150 g, 175 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 97L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "Congee",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 98L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "Cornbread",
                            ServingSize = "\"1 slice, 35 g\""
                        },
                        new
                        {
                            Id = 99L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "Couscous",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 100L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Cracker, saltines\"",
                            ServingSize = "\"10, 30 g\""
                        },
                        new
                        {
                            Id = 101L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"English muffin, white\"",
                            ServingSize = "\"� muffin, 35 g\""
                        },
                        new
                        {
                            Id = 102L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "Naan",
                            ServingSize = "\"� naan, 35 g\""
                        },
                        new
                        {
                            Id = 103L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "Pancake",
                            ServingSize = "\"1 small, 35 g\""
                        },
                        new
                        {
                            Id = 104L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Pasta/noodles, white\"",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 105L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Pita, white\"",
                            ServingSize = "\"� pita, 35 g\""
                        },
                        new
                        {
                            Id = 106L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "Polenta",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 107L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Rice, white\"",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 108L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Rice cake, plain\"",
                            ServingSize = "2 medium"
                        },
                        new
                        {
                            Id = 109L,
                            FoodGroupCategory = 4,
                            FoodGroupId = "gr",
                            Foods = "\"Roll, white\"",
                            ServingSize = "\"1 roll, 35 g\""
                        },
                        new
                        {
                            Id = 110L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Crackers, whole wheat\"",
                            ServingSize = "30 g"
                        },
                        new
                        {
                            Id = 111L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Rice, wild\"",
                            ServingSize = "\"125 mL, � cup cooked\""
                        },
                        new
                        {
                            Id = 112L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Roll, whole wheat\"",
                            ServingSize = "\"1 roll, 35 g\""
                        },
                        new
                        {
                            Id = 113L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Couscous, whole wheat\"",
                            ServingSize = "\"125 mL, � cup - cooked\""
                        },
                        new
                        {
                            Id = 114L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"Popcorn, without added fat or salt\"",
                            ServingSize = "\"500 mL, 2 cups\""
                        },
                        new
                        {
                            Id = 115L,
                            FoodGroupCategory = 3,
                            FoodGroupId = "gr",
                            Foods = "\"English muffin, whole grain\"",
                            ServingSize = "\"� muffin, 35 g\""
                        },
                        new
                        {
                            Id = 116L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "Buttermilk",
                            ServingSize = "\"250 mL, 1 cup\""
                        },
                        new
                        {
                            Id = 117L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "Fortified soy beverage (unsweetened) ",
                            ServingSize = "\"250 mL, 1 cup\""
                        },
                        new
                        {
                            Id = 118L,
                            FoodGroupCategory = 5,
                            FoodGroupId = "mi",
                            Foods = "\"Milk, 1%, 2%, skim\"",
                            ServingSize = "\"250 mL, 1 cup\""
                        },
                        new
                        {
                            Id = 119L,
                            FoodGroupCategory = 5,
                            FoodGroupId = "mi",
                            Foods = "\"Milk, evaporated, canned\"",
                            ServingSize = "\"125 mL, � cup undiluted\""
                        },
                        new
                        {
                            Id = 120L,
                            FoodGroupCategory = 5,
                            FoodGroupId = "mi",
                            Foods = "\"Milk, goat, enriched\"",
                            ServingSize = "\"250 mL, 1 cup\""
                        },
                        new
                        {
                            Id = 121L,
                            FoodGroupCategory = 5,
                            FoodGroupId = "mi",
                            Foods = "\"Milk, lactose reduced\"",
                            ServingSize = "\"250 mL, 1 cup\""
                        },
                        new
                        {
                            Id = 122L,
                            FoodGroupCategory = 5,
                            FoodGroupId = "mi",
                            Foods = "\"Milk, powdered\"",
                            ServingSize = "\"250 mL, 1 cup reconstitued\""
                        },
                        new
                        {
                            Id = 123L,
                            FoodGroupCategory = 5,
                            FoodGroupId = "mi",
                            Foods = "\"Milk, powdered\"",
                            ServingSize = "\"25 g, 75 mL, 1/3 cup\""
                        },
                        new
                        {
                            Id = 124L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "\"Cheese, block (Cheddar, Mozzarella, Swiss, feta)\"",
                            ServingSize = "\"50 g, 1 , � oz\""
                        },
                        new
                        {
                            Id = 125L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "\"Cheese, cottage or quark\"",
                            ServingSize = "\"250 ml, 1 cup\""
                        },
                        new
                        {
                            Id = 126L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "\"Cheese, goat\"",
                            ServingSize = "\"50 g, 1 , � oz\""
                        },
                        new
                        {
                            Id = 127L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "Paneer",
                            ServingSize = "\"50 g, 1 , � oz\""
                        },
                        new
                        {
                            Id = 128L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "\"Yogurt, plain\"",
                            ServingSize = "\"175 g, 175ml, � cup\""
                        },
                        new
                        {
                            Id = 129L,
                            FoodGroupCategory = 5,
                            FoodGroupId = "mi",
                            Foods = "\"Milk, whole\"",
                            ServingSize = "\"250 mL, 1 cup\""
                        },
                        new
                        {
                            Id = 130L,
                            FoodGroupCategory = 6,
                            FoodGroupId = "mi",
                            Foods = "Kefir",
                            ServingSize = "\"175 g, 175 mL, � cup\""
                        },
                        new
                        {
                            Id = 131L,
                            FoodGroupCategory = 7,
                            FoodGroupId = "me",
                            Foods = "\"Beans, cooked and canned\"",
                            ServingSize = "\"175 mL, � cup\""
                        },
                        new
                        {
                            Id = 132L,
                            FoodGroupCategory = 7,
                            FoodGroupId = "me",
                            Foods = "Eggs",
                            ServingSize = "2"
                        },
                        new
                        {
                            Id = 133L,
                            FoodGroupCategory = 7,
                            FoodGroupId = "me",
                            Foods = "Lentils",
                            ServingSize = "\"175 mL, � cup\""
                        },
                        new
                        {
                            Id = 134L,
                            FoodGroupCategory = 7,
                            FoodGroupId = "me",
                            Foods = "\"Nuts, shelled\"",
                            ServingSize = "\"60 mL, � cup\""
                        },
                        new
                        {
                            Id = 135L,
                            FoodGroupCategory = 7,
                            FoodGroupId = "me",
                            Foods = "Peanut butter or nut butters",
                            ServingSize = "\"30 mL, 2 Tbsp\""
                        },
                        new
                        {
                            Id = 136L,
                            FoodGroupCategory = 7,
                            FoodGroupId = "me",
                            Foods = "\"Seeds, shelled\"",
                            ServingSize = "\"60 mL, � cup\""
                        },
                        new
                        {
                            Id = 137L,
                            FoodGroupCategory = 7,
                            FoodGroupId = "me",
                            Foods = "Tofu",
                            ServingSize = "\"150 g, 175 mL, � cup\""
                        },
                        new
                        {
                            Id = 138L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Beef",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 139L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Bison/Buffalo",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 140L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Chicken",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 141L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "\"Deli meat, low-fat, lower sodium\"",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 142L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Duck",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 143L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "\"Fish and shellfish, canned (example: crab, salmon, tuna)\"",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 144L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "\"Fish, fresh or frozen (example: herring, mackerel, trout, salmon, sardines, squid, tuna)\"",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 145L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "\"Game birds (example: ptarmigan, partridge, grouse, goose)\"",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 146L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "\"Game meats (example: deer, moose, caribou, elk)\"",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 147L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Goat",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 148L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Ham",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 149L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Lamb",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 150L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "\"Organ meat (example: liver, kidney)\"",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 151L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Pork",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 152L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Rabbit /Hare",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 153L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "\"Shellfish, fresh or frozen (example: clams, crab, lobster, mussels, scallops, shrimp, prawns)\"",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 154L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Turkey",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        },
                        new
                        {
                            Id = 155L,
                            FoodGroupCategory = 8,
                            FoodGroupId = "me",
                            Foods = "Veal",
                            ServingSize = "75 g (2� oz) / 125 mL (� cup)"
                        });
                });

            modelBuilder.Entity("FoodApp.Domain.Model.FoodGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FoodGroupCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FoodGroupCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FoodGroupCategoryId = 1,
                            FoodGroupCategoryName = "Non dark green or orange vegetable",
                            FoodGroupId = "vf",
                            FoodGroupName = "Vegetables and Fruit"
                        },
                        new
                        {
                            Id = 2L,
                            FoodGroupCategoryId = 2,
                            FoodGroupCategoryName = "Dark green vegetable",
                            FoodGroupId = "vf",
                            FoodGroupName = "Vegetables and Fruit"
                        },
                        new
                        {
                            Id = 3L,
                            FoodGroupCategoryId = 3,
                            FoodGroupCategoryName = "Orange vegetable",
                            FoodGroupId = "vf",
                            FoodGroupName = "Vegetables and Fruit"
                        },
                        new
                        {
                            Id = 4L,
                            FoodGroupCategoryId = 5,
                            FoodGroupCategoryName = "Non whole grain",
                            FoodGroupId = "gr",
                            FoodGroupName = "Grains"
                        },
                        new
                        {
                            Id = 5L,
                            FoodGroupCategoryId = 4,
                            FoodGroupCategoryName = "Whole grain",
                            FoodGroupId = "gr",
                            FoodGroupName = "Grains"
                        },
                        new
                        {
                            Id = 6L,
                            FoodGroupCategoryId = 6,
                            FoodGroupCategoryName = "Milk",
                            FoodGroupId = "mi",
                            FoodGroupName = "Milk and Alternatives"
                        },
                        new
                        {
                            Id = 7L,
                            FoodGroupCategoryId = 7,
                            FoodGroupCategoryName = "Milk Alternataives",
                            FoodGroupId = "mi",
                            FoodGroupName = "Milk and Alternatives"
                        },
                        new
                        {
                            Id = 8L,
                            FoodGroupCategoryId = 8,
                            FoodGroupCategoryName = "Meat Alternatives",
                            FoodGroupId = "me",
                            FoodGroupName = "Meat and Alternatives"
                        },
                        new
                        {
                            Id = 9L,
                            FoodGroupCategoryId = 9,
                            FoodGroupCategoryName = "Meat, fish, poultry and shellfish",
                            FoodGroupId = "me",
                            FoodGroupName = "Meat and Alternatives"
                        });
                });

            modelBuilder.Entity("FoodApp.Domain.Model.Serving", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Servings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = "2 to 3",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "4"
                        },
                        new
                        {
                            Id = 2L,
                            Age = "2 to 3",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "4"
                        },
                        new
                        {
                            Id = 3L,
                            Age = "4 to 8",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "5"
                        },
                        new
                        {
                            Id = 4L,
                            Age = "4 to 8",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "5"
                        },
                        new
                        {
                            Id = 5L,
                            Age = "9 to 13",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "6"
                        },
                        new
                        {
                            Id = 6L,
                            Age = "9 to 13",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "6"
                        },
                        new
                        {
                            Id = 7L,
                            Age = "14 to 18",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 8L,
                            Age = "14 to 18",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "8"
                        },
                        new
                        {
                            Id = 9L,
                            Age = "19 to 30",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "7 to 8"
                        },
                        new
                        {
                            Id = 10L,
                            Age = "19 to 30",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "8 to 10"
                        },
                        new
                        {
                            Id = 11L,
                            Age = "31 to 50",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "7 to 8"
                        },
                        new
                        {
                            Id = 12L,
                            Age = "31 to 50",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "8 to 10"
                        },
                        new
                        {
                            Id = 13L,
                            Age = "51 to 70",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 14L,
                            Age = "51 to 70",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 15L,
                            Age = "71+",
                            FoodGroupId = "vf",
                            Gender = "Female",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 16L,
                            Age = "71+",
                            FoodGroupId = "vf",
                            Gender = "Male",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 17L,
                            Age = "2 to 3",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 18L,
                            Age = "2 to 3",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 19L,
                            Age = "4 to 8",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "4"
                        },
                        new
                        {
                            Id = 20L,
                            Age = "4 to 8",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "4"
                        },
                        new
                        {
                            Id = 21L,
                            Age = "9 to 13",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "6"
                        },
                        new
                        {
                            Id = 22L,
                            Age = "9 to 13",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "6"
                        },
                        new
                        {
                            Id = 23L,
                            Age = "14 to 18",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "6"
                        },
                        new
                        {
                            Id = 24L,
                            Age = "14 to 18",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 25L,
                            Age = "19 to 30",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "6 to 7"
                        },
                        new
                        {
                            Id = 26L,
                            Age = "19 to 30",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "8"
                        },
                        new
                        {
                            Id = 27L,
                            Age = "31 to 50",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "6 to 7"
                        },
                        new
                        {
                            Id = 28L,
                            Age = "31 to 50",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "8"
                        },
                        new
                        {
                            Id = 29L,
                            Age = "51 to 70",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "6"
                        },
                        new
                        {
                            Id = 30L,
                            Age = "51 to 70",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 31L,
                            Age = "71+",
                            FoodGroupId = "gr",
                            Gender = "Female",
                            Servings = "6"
                        },
                        new
                        {
                            Id = 32L,
                            Age = "71+",
                            FoodGroupId = "gr",
                            Gender = "Male",
                            Servings = "7"
                        },
                        new
                        {
                            Id = 33L,
                            Age = "2 to 3",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 34L,
                            Age = "2 to 3",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 35L,
                            Age = "4 to 8",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 36L,
                            Age = "4 to 8",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 37L,
                            Age = "9 to 13",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "3 to 4"
                        },
                        new
                        {
                            Id = 38L,
                            Age = "9 to 13",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "3 to 4"
                        },
                        new
                        {
                            Id = 39L,
                            Age = "14 to 18",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "3 to 4"
                        },
                        new
                        {
                            Id = 40L,
                            Age = "14 to 18",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "3 to 4"
                        },
                        new
                        {
                            Id = 41L,
                            Age = "19 to 30",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 42L,
                            Age = "19 to 30",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 43L,
                            Age = "31 to 50",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 44L,
                            Age = "31 to 50",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 45L,
                            Age = "51 to 70",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 46L,
                            Age = "51 to 70",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 47L,
                            Age = "71+",
                            FoodGroupId = "mi",
                            Gender = "Female",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 48L,
                            Age = "71+",
                            FoodGroupId = "mi",
                            Gender = "Male",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 49L,
                            Age = "2 to 3",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "1"
                        },
                        new
                        {
                            Id = 50L,
                            Age = "2 to 3",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "1"
                        },
                        new
                        {
                            Id = 51L,
                            Age = "4 to 8",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "1"
                        },
                        new
                        {
                            Id = 52L,
                            Age = "4 to 8",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "1"
                        },
                        new
                        {
                            Id = 53L,
                            Age = "9 to 13",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "1 to 2"
                        },
                        new
                        {
                            Id = 54L,
                            Age = "9 to 13",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "1 to 2"
                        },
                        new
                        {
                            Id = 55L,
                            Age = "14 to 18",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 56L,
                            Age = "14 to 18",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 57L,
                            Age = "19 to 30",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 58L,
                            Age = "19 to 30",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 59L,
                            Age = "31 to 50",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 60L,
                            Age = "31 to 50",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 61L,
                            Age = "51 to 70",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 62L,
                            Age = "51 to 70",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "3"
                        },
                        new
                        {
                            Id = 63L,
                            Age = "71+",
                            FoodGroupId = "me",
                            Gender = "Female",
                            Servings = "2"
                        },
                        new
                        {
                            Id = 64L,
                            Age = "71+",
                            FoodGroupId = "me",
                            Gender = "Male",
                            Servings = "3"
                        });
                });

            modelBuilder.Entity("FoodApp.Domain.Model.Statement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DirectionalStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodGroupId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statements");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DirectionalStatement = "Eat at least one dark green and one orange vegetable each day.",
                            FoodGroupId = "vf"
                        },
                        new
                        {
                            Id = 2L,
                            DirectionalStatement = "\"Choose vegetables and fruit prepared with little or no added fat, sugar or salt.\"",
                            FoodGroupId = "vf"
                        },
                        new
                        {
                            Id = 3L,
                            DirectionalStatement = "Have vegetables and fruit more often than juice.",
                            FoodGroupId = "vf"
                        },
                        new
                        {
                            Id = 4L,
                            DirectionalStatement = "Make at least half of your grain products whole grain each day.",
                            FoodGroupId = "gr"
                        },
                        new
                        {
                            Id = 5L,
                            DirectionalStatement = "\"Choose grain products that are lower in fat, sugar or salt.\"",
                            FoodGroupId = "gr"
                        },
                        new
                        {
                            Id = 6L,
                            DirectionalStatement = "\"Drink skim, 1%, or 2% milk each day.\"",
                            FoodGroupId = "mi"
                        },
                        new
                        {
                            Id = 7L,
                            DirectionalStatement = "Select lower fat milk alternatives.",
                            FoodGroupId = "mi"
                        },
                        new
                        {
                            Id = 8L,
                            DirectionalStatement = "\"Have meat alternatives such as beans, lentils and tofu often.\"",
                            FoodGroupId = "me"
                        },
                        new
                        {
                            Id = 9L,
                            DirectionalStatement = "Eat at least two Food Guide Servings of fish each week.",
                            FoodGroupId = "me"
                        },
                        new
                        {
                            Id = 10L,
                            DirectionalStatement = "Select lean meat and alternatives prepared with little or no added fat or salt.",
                            FoodGroupId = "me"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
